### ISSUE TITLE
Fix cleanup of resources on e2e tests

### ISSUE THREAD

**Issue by mzeevi** [dana-team/rcs-ocm-deployer#35]
Right now the resources created are not deleted at the end of the test, leaving some garbage behind. This ought to be fixed.

/kind tests

**Comment by omer5yerushalmi** [comment]
Kuttl already has that feature, you can see here https://kuttl.dev/docs/testing/reference.html#testsuite.
There is a skipDelete flag which is by default set to `false`: "If set, do not delete the resources after running the tests (implies SkipClusterDelete)."
