### ISSUE TITLE
DomainMapping v1alpha1 becomes deprecated

### ISSUE THREAD

**Issue by omerbd21** [dana-team/rcs-ocm-deployer#74]
"API Warning: The v1alpha1 version of DomainMapping has been deprecated and will be removed in a future release of the API. Please upgrade to v1beta1"
is being logged to knative-serving controller.
We need to upgrade the version to v1beta1.

**Comment by fran2810** [comment]
Fixed by https://github.com/dana-team/container-app-operator/pull/84
