### ISSUE TITLE
Missing RBAC permissions for controller service account

### ISSUE THREAD

**Issue by omerbd21** [dana-team/rcs-ocm-deployer#76]
When running RCS from the main branch, we are missing these permissions:
//+kubebuilder:rbac:groups=rcs.dana.io,resources=capps/status,verbs=update
//+kubebuilder:rbac:groups=work.open-cluster-management.io,resources=manifestworks,verbs=get;list;watch;create;patch;update;delete
//+kubebuilder:rbac:groups="rcsd.dana.io",resources=rcsconfigs,verbs=get;list;watch
//+kubebuilder:rbac:groups="rbac.authorization.k8s.io",resources=rolebindings,verbs=get;list;watch

**Comment by fran2810** [comment]
Fixed by #78
